services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_clean_architect
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - symfony

  nginx:
    image: nginx:1.23-alpine
    container_name: symfony_nginx
    ports:
      - "8090:8090"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3307:3306"
    networks:
      - symfony
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  mongodb:
    container_name: symfony_mongodb
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1
    ports:
      - "${MONGODB_PORT-27011}:27017"
    networks:
      - symfony
networks:
  symfony:
    driver: bridge
